# Generated by Django 2.2.24 on 2021-10-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0044_auto_20210126_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeresource',
            name='cost_usd',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='computeresource',
            name='cpus',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='computeresource',
            name='gpus',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
