# Generated by Django 2.2.24 on 2021-10-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0046_auto_20211025_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeresource',
            name='workers',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
