# Generated by Django 2.2.24 on 2021-11-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0047_computeresource_workers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computeresource',
            old_name='cpu_power',
            new_name='cpu_clock_speed_ghz',
        ),
        migrations.RenameField(
            model_name='computeresource',
            old_name='gpu_power',
            new_name='gpu_memory',
        ),
        migrations.RemoveField(
            model_name='computeresource',
            name='cpu_power_unit',
        ),
        migrations.RemoveField(
            model_name='computeresource',
            name='gpu_power_unit',
        ),
        migrations.RemoveField(
            model_name='computeresource',
            name='memory_unit',
        ),
    ]
